Feature/sshd customization
42ity/fty-core pull request #483
Opened 2021-02-12 16:24 UTC by MimiXav

2021-02-12 16:57 UTC, jeffdegott approved these changes

2021-02-12 17:15 UTC, jimklimov commented
I am not sure this would work: on one hand, you probably meant /etc/pam.d/sshd and on another - files are likely to exist in advance so `ln` would not replace them. It can replace symlinks with `-f` flag though.

2021-02-12 17:17 UTC, jimklimov commented
Also, in the age of chroots, containers and such, prefer to forget about making absolute symlinks - to avoid surprises when looking into the OS image from its hoster env, into backups, etc. `ln -srf` is your friend here.

2021-02-12 17:22 UTC, jimklimov commented
Also just in case: for our product this change fixes up the R/O root in the OS image. If someone changed these file in a live deployed system (not sure if these two do get configured in practice),  then copies in overlayfs would be applied after upgrade regardless of squashfs changes. If this is not desired, you may want ipc-meta-setup scriptlets instead, to patch an existing overlaid-or-not filesystem for a predictable result.

2021-02-15 11:04 UTC, perrettecl requested changes

2021-02-15 11:04 UTC, perrettecl commented on obs/preinstallimage-bios.sh.in
> +  ln -s /etc/template-sshd /etc/sshd
use ln -srf

2021-02-18 09:01 UTC, MimiXav commented on obs/preinstallimage-bios.sh.in
> +  ln -s /etc/template-sshd /etc/sshd
Done

2021-02-18 10:41 UTC, perrettecl approved these changes

2021-02-18 10:41 UTC, merged

2021-02-18 12:23 UTC, jimklimov commented
in init-os-accounts this still changes the parent system (e.g. developer workstation) and not one in ALTROOT (e.g. their container).

Also if you do need the custom nsswitch config in the product OS image, the preinstallimage script by itself currently does not make it happen.